// Code generated by hertz generator.

package stash

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	stash "github.com/yi-nology/git-manage-service/biz/model/stash"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/handler"
)

// ListStash .
// @router /api/v1/stash/list [GET]
func ListStash(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepo(c,
		func(r *stash.ListStashRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *stash.ListStashRequest) (any, error) {
			return git.NewGitService().StashList(repo.Path)
		},
	)
}

// SaveStash .
// @router /api/v1/stash/save [POST]
func SaveStash(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepoVoid(c,
		func(r *stash.SaveStashRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *stash.SaveStashRequest) error {
			return git.NewGitService().StashSave(repo.Path, req.Message, req.IncludeUntracked)
		},
	)
}

// ApplyStash .
// @router /api/v1/stash/apply [POST]
func ApplyStash(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepoVoid(c,
		func(r *stash.ApplyStashRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *stash.ApplyStashRequest) error {
			return git.NewGitService().StashApply(repo.Path, int(req.Index))
		},
	)
}

// PopStash .
// @router /api/v1/stash/pop [POST]
func PopStash(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepoVoid(c,
		func(r *stash.PopStashRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *stash.PopStashRequest) error {
			return git.NewGitService().StashPop(repo.Path, int(req.Index))
		},
	)
}

// DropStash .
// @router /api/v1/stash/drop [POST]
func DropStash(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepoVoid(c,
		func(r *stash.DropStashRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *stash.DropStashRequest) error {
			return git.NewGitService().StashDrop(repo.Path, int(req.Index))
		},
	)
}

// ClearStash .
// @router /api/v1/stash/clear [POST]
func ClearStash(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepoVoid(c,
		func(r *stash.ClearStashRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *stash.ClearStashRequest) error {
			return git.NewGitService().StashClear(repo.Path)
		},
	)
}
