// Code generated by hertz generator.

package mirror

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mirrorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmirrorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _analyzeremoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatecredentialMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemirrorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsynclogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pausemirrorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _previewsyncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resumemirrorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _triggersyncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemirrorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _log_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsynclogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletesynclogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _webhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlewebhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mirrorsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmirrorsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchtriggersyncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mirror0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmirrorMw() []app.HandlerFunc {
	// your code...
	return nil
}
