// Code generated by hertz generator.

package workspace

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workspaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _airesolveconflictMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commitchangesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconflictdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkspacediffMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pullwithresolveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _markconflictresolvedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stagefilesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkspacestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unstagefilesMw() []app.HandlerFunc {
	// your code...
	return nil
}
