// Code generated by hertz generator.

package review

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	"github.com/yi-nology/git-manage-service/biz/model/api"
	codereview "github.com/yi-nology/git-manage-service/biz/service/codereview"
	pkgresponse "github.com/yi-nology/git-manage-service/pkg/response"
)

func CreateTask(ctx context.Context, c *app.RequestContext) {
	var req struct {
		RepoKey          string `json:"repo_key"`
		ProviderConfigID uint   `json:"provider_config_id"`
		MRIID            string `json:"mr_iid"`
		CommitSHA        string `json:"commit_sha"`
		TriggerType      string `json:"trigger_type"`
	}
	if err := c.BindAndValidate(&req); err != nil {
		pkgresponse.BadRequest(c, err.Error())
		return
	}
	if req.RepoKey == "" || req.MRIID == "" {
		pkgresponse.BadRequest(c, "repo_key and mr_iid are required")
		return
	}
	if req.TriggerType == "" {
		req.TriggerType = "manual"
	}
	task, err := codereview.CreateTask(ctx, req.RepoKey, req.ProviderConfigID, req.MRIID, req.CommitSHA, req.TriggerType)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	c.Set("audit_target", "repo:"+req.RepoKey)
	c.Set("audit_details", map[string]string{"mr_iid": req.MRIID, "trigger": req.TriggerType})
	pkgresponse.Success(c, api.NewReviewTaskDTO(*task))
}

func GetTask(ctx context.Context, c *app.RequestContext) {
	id, err := parseID(c.Param("id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid id")
		return
	}
	task, err := db.NewReviewTaskDAO().FindByID(id)
	if err != nil {
		pkgresponse.NotFound(c, "review task not found")
		return
	}
	dto := api.NewReviewTaskDTO(*task)
	findingCount, _ := db.NewReviewFindingDAO().CountByTaskID(id)
	dto.FindingsCount = int(findingCount)
	pkgresponse.Success(c, dto)
}

func ListTasks(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	status := c.Query("status")
	_ = c.Query("mr_iid")
	page, _ := strconv.Atoi(c.DefaultQuery("page", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "20"))
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 100 {
		pageSize = 20
	}

	if repoKey == "" {
		pkgresponse.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		pkgresponse.NotFound(c, "repo not found")
		return
	}

	tasks, total, err := db.NewReviewTaskDAO().FindByRepoID(repo.ID, status, page, pageSize)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}

	dtos := make([]api.ReviewTaskDTO, 0, len(tasks))
	for _, t := range tasks {
		dto := api.NewReviewTaskDTO(t)
		dto.RepoKey = repoKey
		dto.RepoName = repo.Name
		dtos = append(dtos, dto)
	}

	pkgresponse.Success(c, map[string]interface{}{
		"tasks": dtos,
		"pagination": map[string]interface{}{
			"total":    total,
			"page":     page,
			"pageSize": pageSize,
		},
	})
}

func ListFindings(ctx context.Context, c *app.RequestContext) {
	taskID, err := parseID(c.Param("task_id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid task_id")
		return
	}
	severity := c.Query("severity")
	source := c.Query("source")

	findings, err := db.NewReviewFindingDAO().FindByTaskID(taskID, severity, source)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}

	dtos := make([]api.ReviewFindingDTO, 0, len(findings))
	for _, f := range findings {
		dtos = append(dtos, api.NewReviewFindingDTO(f))
	}
	pkgresponse.Success(c, dtos)
}

func RetryTask(ctx context.Context, c *app.RequestContext) {
	id, err := parseID(c.Param("id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid id")
		return
	}
	task, err := codereview.RetryTask(ctx, id)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, api.NewReviewTaskDTO(*task))
}

func CheckMerge(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	mrIID := c.Query("mr_iid")
	commitSHA := c.Query("commit_sha")
	if repoKey == "" || mrIID == "" {
		pkgresponse.BadRequest(c, "repo_key and mr_iid are required")
		return
	}

	result, err := codereview.CheckMerge(ctx, repoKey, mrIID, commitSHA)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, result)
}

func GetReviewConfig(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Param("repo_key")
	if repoKey == "" {
		pkgresponse.BadRequest(c, "repo_key is required")
		return
	}
	config, err := codereview.GetReviewConfig(repoKey)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, map[string]string{"config_yaml": config})
}

func UpdateReviewConfig(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Param("repo_key")
	var req struct {
		ConfigYAML string `json:"config_yaml"`
	}
	if err := c.BindAndValidate(&req); err != nil {
		pkgresponse.BadRequest(c, err.Error())
		return
	}
	if err := codereview.UpdateReviewConfig(repoKey, req.ConfigYAML); err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	c.Set("audit_target", "repo:"+repoKey)
	pkgresponse.Success(c, map[string]string{"config_yaml": req.ConfigYAML})
}

func GetRemoteRepoConfig(ctx context.Context, c *app.RequestContext) {
	providerID, err := parseID(c.Param("provider_id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid provider_id")
		return
	}
	owner := c.Param("owner")
	repo := strings.TrimPrefix(c.Param("repo"), "/")
	if owner == "" || repo == "" {
		pkgresponse.BadRequest(c, "owner and repo are required")
		return
	}
	result, err := codereview.GetRemoteRepoConfig(providerID, owner, repo)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, result)
}

func UpdateRemoteRepoConfig(ctx context.Context, c *app.RequestContext) {
	providerID, err := parseID(c.Param("provider_id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid provider_id")
		return
	}
	owner := c.Param("owner")
	repo := strings.TrimPrefix(c.Param("repo"), "/")
	if owner == "" || repo == "" {
		pkgresponse.BadRequest(c, "owner and repo are required")
		return
	}
	var req api.ReviewRepoConfigDTO
	if err := c.BindAndValidate(&req); err != nil {
		pkgresponse.BadRequest(c, err.Error())
		return
	}
	result, err := codereview.UpdateRemoteRepoConfig(providerID, owner, repo, req)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	c.Set("audit_target", fmt.Sprintf("provider:%d:%s/%s", providerID, owner, repo))
	pkgresponse.Success(c, result)
}

func parseID(s string) (uint, error) {
	id, err := strconv.ParseUint(s, 10, 32)
	if err != nil {
		return 0, err
	}
	return uint(id), nil
}
