// Code generated by hertz generator.

package review

import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	"github.com/yi-nology/git-manage-service/biz/model/api"
	reviewModel "github.com/yi-nology/git-manage-service/biz/model/review"
	codereview "github.com/yi-nology/git-manage-service/biz/service/codereview"
	"github.com/yi-nology/git-manage-service/biz/service/rag"
	pkgresponse "github.com/yi-nology/git-manage-service/pkg/response"
)

var repoKeyPattern = regexp.MustCompile(`^[a-zA-Z0-9._/\-]{1,255}$`)

func validateRepoKey(key string) bool {
	return repoKeyPattern.MatchString(key)
}

func validateSHA(sha string) bool {
	if len(sha) == 0 || len(sha) > 128 {
		return false
	}
	for _, c := range sha {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
			return false
		}
	}
	return true
}

func validateMRIID(s string) bool {
	if len(s) == 0 || len(s) > 64 {
		return false
	}
	for _, c := range s {
		if !(c >= '0' && c <= '9') {
			return false
		}
	}
	return true
}

func validateSeverity(s string) bool {
	switch s {
	case "", "critical", "high", "medium", "low", "info":
		return true
	}
	return false
}

func validateSource(s string) bool {
	switch s {
	case "", "rule", "llm":
		return true
	}
	return false
}

func convertToProtoReviewTask(dto api.ReviewTaskDTO) *reviewModel.ReviewTask {
	return &reviewModel.ReviewTask{
		Id:               uint64(dto.ID),
		RepoId:           uint64(dto.RepoID),
		ProviderConfigId: uint64(dto.ProviderConfigID),
		Platform:         dto.Platform,
		EventType:        dto.EventType,
		MrIid:            dto.MRIID,
		SourceBranch:     dto.SourceBranch,
		TargetBranch:     dto.TargetBranch,
		CommitSha:        dto.CommitSHA,
		TriggerType:      dto.TriggerType,
		TriggerUser:      dto.TriggerUser,
		Status:           dto.Status,
		RiskLevel:        dto.RiskLevel,
		Summary:          dto.Summary,
		ErrorMessage:     dto.ErrorMessage,
		CreatedAt:        dto.CreatedAt.Format("2006-01-02T15:04:05Z"),
		UpdatedAt:        dto.UpdatedAt.Format("2006-01-02T15:04:05Z"),
	}
}

func convertToProtoReviewFinding(dto api.ReviewFindingDTO) *reviewModel.ReviewFinding {
	return &reviewModel.ReviewFinding{
		Id:          uint64(dto.ID),
		TaskId:      uint64(dto.TaskID),
		Source:      dto.Source,
		RuleId:      dto.RuleID,
		Severity:    dto.Severity,
		FilePath:    dto.FilePath,
		OldLine:     int32(dto.OldLine),
		NewLine:     int32(dto.NewLine),
		Title:       dto.Title,
		Message:     dto.Message,
		Suggestion:  dto.Suggestion,
		Fingerprint: dto.Fingerprint,
	}
}

func CreateTask(ctx context.Context, c *app.RequestContext) {
	var req struct {
		RepoKey          string `json:"repo_key"`
		ProviderConfigID uint   `json:"provider_config_id"`
		MRIID            string `json:"mr_iid"`
		CommitSHA        string `json:"commit_sha"`
		TriggerType      string `json:"trigger_type"`
	}
	if err := c.BindAndValidate(&req); err != nil {
		pkgresponse.BadRequest(c, err.Error())
		return
	}
	if req.RepoKey == "" || req.MRIID == "" {
		pkgresponse.BadRequest(c, "repo_key and mr_iid are required")
		return
	}
	if !validateRepoKey(req.RepoKey) {
		pkgresponse.BadRequest(c, "repo_key contains invalid characters or exceeds 255 chars")
		return
	}
	if !validateMRIID(req.MRIID) {
		pkgresponse.BadRequest(c, "mr_iid must be a numeric string (max 64 chars)")
		return
	}
	if req.CommitSHA != "" && !validateSHA(req.CommitSHA) {
		pkgresponse.BadRequest(c, "commit_sha must be a valid hex string (max 128 chars)")
		return
	}
	if req.TriggerType == "" {
		req.TriggerType = "manual"
	}
	task, err := codereview.CreateTask(ctx, req.RepoKey, req.ProviderConfigID, req.MRIID, req.CommitSHA, req.TriggerType)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	c.Set("audit_target", "repo:"+req.RepoKey)
	c.Set("audit_details", map[string]string{"mr_iid": req.MRIID, "trigger": req.TriggerType})
	pkgresponse.Success(c, convertToProtoReviewTask(api.NewReviewTaskDTO(*task)))
}

func GetTask(ctx context.Context, c *app.RequestContext) {
	id, err := parseID(c.Param("id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid id")
		return
	}
	task, err := db.NewReviewTaskDAO().FindByID(id)
	if err != nil {
		pkgresponse.NotFound(c, "review task not found")
		return
	}
	dto := api.NewReviewTaskDTO(*task)
	findingCount, _ := db.NewReviewFindingDAO().CountByTaskID(id)
	dto.FindingsCount = int(findingCount)
	pkgresponse.Success(c, dto)
}

func ListTasks(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	status := c.Query("status")
	_ = c.Query("mr_iid")
	page, _ := strconv.Atoi(c.DefaultQuery("page", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "20"))
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 100 {
		pageSize = 20
	}

	if repoKey == "" {
		pkgresponse.BadRequest(c, "repo_key is required")
		return
	}
	if !validateRepoKey(repoKey) {
		pkgresponse.BadRequest(c, "repo_key contains invalid characters or exceeds 255 chars")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		pkgresponse.NotFound(c, "repo not found")
		return
	}

	tasks, total, err := db.NewReviewTaskDAO().FindByRepoID(repo.ID, status, page, pageSize)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}

	dtos := make([]*reviewModel.ReviewTask, 0, len(tasks))
	for _, t := range tasks {
		dto := api.NewReviewTaskDTO(t)
		dto.RepoKey = repoKey
		dto.RepoName = repo.Name
		dtos = append(dtos, convertToProtoReviewTask(dto))
	}

	pkgresponse.Success(c, map[string]interface{}{
		"tasks": dtos,
		"pagination": map[string]interface{}{
			"total":    total,
			"page":     page,
			"pageSize": pageSize,
		},
	})
}

func ListFindings(ctx context.Context, c *app.RequestContext) {
	taskID, err := parseID(c.Param("task_id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid task_id")
		return
	}
	severity := c.Query("severity")
	source := c.Query("source")
	if !validateSeverity(severity) {
		pkgresponse.BadRequest(c, "invalid severity filter, must be one of: critical, high, medium, low, info")
		return
	}
	if !validateSource(source) {
		pkgresponse.BadRequest(c, "invalid source filter, must be one of: rule, llm")
		return
	}

	findings, err := db.NewReviewFindingDAO().FindByTaskID(taskID, severity, source)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}

	seen := make(map[string]bool, len(findings))
	dtos := make([]*reviewModel.ReviewFinding, 0, len(findings))
	for _, f := range findings {
		key := f.Source + ":" + f.FilePath + ":" + f.RuleID + ":" + fmt.Sprintf("%d", f.NewLine)
		if seen[key] {
			continue
		}
		seen[key] = true
		dtos = append(dtos, convertToProtoReviewFinding(api.NewReviewFindingDTO(f)))
	}
	pkgresponse.Success(c, dtos)
}

func RetryTask(ctx context.Context, c *app.RequestContext) {
	id, err := parseID(c.Param("id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid id")
		return
	}
	var body struct {
		Owner string `json:"owner"`
		Repo  string `json:"repo"`
	}
	_ = c.BindAndValidate(&body)
	task, err := codereview.RetryTask(ctx, id, body.Owner, body.Repo)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, convertToProtoReviewTask(api.NewReviewTaskDTO(*task)))
}

func CheckMerge(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	mrIID := c.Query("mr_iid")
	commitSHA := c.Query("commit_sha")
	if repoKey == "" || mrIID == "" {
		pkgresponse.BadRequest(c, "repo_key and mr_iid are required")
		return
	}
	if !validateRepoKey(repoKey) {
		pkgresponse.BadRequest(c, "repo_key contains invalid characters or exceeds 255 chars")
		return
	}
	if !validateMRIID(mrIID) {
		pkgresponse.BadRequest(c, "mr_iid must be a numeric string (max 64 chars)")
		return
	}
	if commitSHA != "" && !validateSHA(commitSHA) {
		pkgresponse.BadRequest(c, "commit_sha must be a valid hex string (max 128 chars)")
		return
	}

	result, err := codereview.CheckMerge(ctx, repoKey, mrIID, commitSHA)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, result)
}

func GetReviewConfig(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Param("repo_key")
	if repoKey == "" || !validateRepoKey(repoKey) {
		pkgresponse.BadRequest(c, "valid repo_key is required")
		return
	}
	config, err := codereview.GetReviewConfig(repoKey)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, map[string]string{"config_yaml": config})
}

func UpdateReviewConfig(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Param("repo_key")
	var req struct {
		ConfigYAML string `json:"config_yaml"`
	}
	if err := c.BindAndValidate(&req); err != nil {
		pkgresponse.BadRequest(c, err.Error())
		return
	}
	if err := codereview.UpdateReviewConfig(repoKey, req.ConfigYAML); err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	c.Set("audit_target", "repo:"+repoKey)
	pkgresponse.Success(c, map[string]string{"config_yaml": req.ConfigYAML})
}

func GetRemoteRepoConfig(ctx context.Context, c *app.RequestContext) {
	providerID, err := parseID(c.Param("provider_id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid provider_id")
		return
	}
	owner := c.Param("owner")
	repo := strings.TrimPrefix(c.Param("repo"), "/")
	if owner == "" || repo == "" {
		pkgresponse.BadRequest(c, "owner and repo are required")
		return
	}
	result, err := codereview.GetRemoteRepoConfig(providerID, owner, repo)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, result)
}

func UpdateRemoteRepoConfig(ctx context.Context, c *app.RequestContext) {
	providerID, err := parseID(c.Param("provider_id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid provider_id")
		return
	}
	owner := c.Param("owner")
	repo := strings.TrimPrefix(c.Param("repo"), "/")
	if owner == "" || repo == "" {
		pkgresponse.BadRequest(c, "owner and repo are required")
		return
	}
	var req api.ReviewRepoConfigDTO
	if err := c.BindAndValidate(&req); err != nil {
		pkgresponse.BadRequest(c, err.Error())
		return
	}
	result, err := codereview.UpdateRemoteRepoConfig(providerID, owner, repo, req)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	c.Set("audit_target", fmt.Sprintf("provider:%d:%s/%s", providerID, owner, repo))
	pkgresponse.Success(c, result)
}

func parseID(s string) (uint, error) {
	id, err := strconv.ParseUint(s, 10, 32)
	if err != nil {
		return 0, err
	}
	return uint(id), nil
}

func GetReviewStats(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	period := c.DefaultQuery("period", "7d")

	if repoKey != "" && !validateRepoKey(repoKey) {
		pkgresponse.BadRequest(c, "repo_key contains invalid characters or exceeds 255 chars")
		return
	}

	var repoID uint
	if repoKey != "" {
		repo, err := db.NewRepoDAO().FindByKey(repoKey)
		if err != nil {
			pkgresponse.NotFound(c, "repo not found")
			return
		}
		repoID = repo.ID
	}

	stats := codereview.GetReviewStats(repoID, period)
	pkgresponse.Success(c, stats)
}

func GetReviewFeedback(ctx context.Context, c *app.RequestContext) {
	findingID, err := parseID(c.Param("finding_id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid finding_id")
		return
	}
	var req struct {
		Feedback string `json:"feedback"`
	}
	if err := c.BindAndValidate(&req); err != nil {
		pkgresponse.BadRequest(c, err.Error())
		return
	}
	if req.Feedback != "useful" && req.Feedback != "false_positive" {
		pkgresponse.BadRequest(c, "feedback must be 'useful' or 'false_positive'")
		return
	}
	if err := db.NewReviewFindingDAO().UpdateFeedback(findingID, req.Feedback); err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	pkgresponse.Success(c, map[string]string{"status": "updated"})
}

func CreateTaskByProvider(ctx context.Context, c *app.RequestContext) {
	var req struct {
		ProviderConfigID uint   `json:"provider_config_id"`
		Owner            string `json:"owner"`
		Repo             string `json:"repo"`
		MRIID            string `json:"mr_iid"`
		CommitSHA        string `json:"commit_sha"`
		TriggerType      string `json:"trigger_type"`
	}
	if err := c.BindAndValidate(&req); err != nil {
		pkgresponse.BadRequest(c, err.Error())
		return
	}
	if req.ProviderConfigID == 0 || req.MRIID == "" {
		pkgresponse.BadRequest(c, "provider_config_id and mr_iid are required")
		return
	}
	if !validateMRIID(req.MRIID) {
		pkgresponse.BadRequest(c, "mr_iid must be a numeric string (max 64 chars)")
		return
	}
	if req.CommitSHA != "" && !validateSHA(req.CommitSHA) {
		pkgresponse.BadRequest(c, "commit_sha must be a valid hex string (max 128 chars)")
		return
	}
	if req.TriggerType == "" {
		req.TriggerType = "manual"
	}
	task, err := codereview.CreateTaskByProvider(ctx, req.ProviderConfigID, req.Owner, req.Repo, req.MRIID, req.CommitSHA, req.TriggerType)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	c.Set("audit_target", fmt.Sprintf("provider:%d", req.ProviderConfigID))
	pkgresponse.Success(c, convertToProtoReviewTask(api.NewReviewTaskDTO(*task)))
}

func ListTasksByProvider(ctx context.Context, c *app.RequestContext) {
	providerID, err := parseID(c.Query("provider_id"))
	if err != nil {
		pkgresponse.BadRequest(c, "invalid provider_id")
		return
	}
	mrIID := c.Query("mr_iid")
	if mrIID != "" && !validateMRIID(mrIID) {
		pkgresponse.BadRequest(c, "mr_iid must be a numeric string (max 64 chars)")
		return
	}
	status := c.Query("status")
	page, _ := strconv.Atoi(c.DefaultQuery("page", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "20"))
	if page < 1 {
		page = 1
	}
	if pageSize < 1 || pageSize > 100 {
		pageSize = 20
	}

	tasks, total, err := db.NewReviewTaskDAO().FindByProviderConfigID(providerID, mrIID, page, pageSize)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}

	_ = status

	dtos := make([]*reviewModel.ReviewTask, 0, len(tasks))
	for _, t := range tasks {
		dto := api.NewReviewTaskDTO(t)
		findingCount, _ := db.NewReviewFindingDAO().CountByTaskID(t.ID)
		dto.FindingsCount = int(findingCount)
		dtos = append(dtos, convertToProtoReviewTask(dto))
	}

	pkgresponse.Success(c, map[string]interface{}{
		"tasks": dtos,
		"pagination": map[string]interface{}{
			"total":    total,
			"page":     page,
			"pageSize": pageSize,
		},
	})
}

func IndexRepoRAG(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Param("repo_key")
	if repoKey == "" || !validateRepoKey(repoKey) {
		pkgresponse.BadRequest(c, "valid repo_key is required")
		return
	}

	svc := rag.DefaultService()
	if !svc.IsAvailable() {
		pkgresponse.BadRequest(c, "RAG service not available (embedding client not configured)")
		return
	}

	result, err := svc.IndexRepo(ctx, repoKey)
	if err != nil {
		pkgresponse.InternalServerError(c, err.Error())
		return
	}
	c.Set("audit_target", "rag:"+repoKey)
	pkgresponse.Success(c, result)
}

func GetRAGStats(ctx context.Context, c *app.RequestContext) {
	store := rag.DefaultStore()
	pkgresponse.Success(c, map[string]interface{}{
		"stats":     store.Stats(),
		"available": rag.DefaultService().IsAvailable(),
	})
}

func GetPromptStructure(ctx context.Context, c *app.RequestContext) {
	structure := codereview.GetPromptStructure()
	pkgresponse.Success(c, structure)
}
