// Code generated by hertz generator.

package sshkey

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	sshkey "github.com/yi-nology/git-manage-service/biz/model/sshkey"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/handler"
	"github.com/yi-nology/git-manage-service/pkg/response"
	"github.com/yi-nology/git-manage-service/pkg/timefmt"
)

// ListDBSSHKeys .
// @router /api/v1/system/db-ssh-keys [GET]
func ListDBSSHKeys(ctx context.Context, c *app.RequestContext) {
	sshKeyDAO := db.NewSSHKeyDAO()
	keys, err := sshKeyDAO.FindAll()
	if err != nil {
		response.InternalServerError(c, "Failed to fetch SSH keys: "+err.Error())
		return
	}

	var dbKeys []*sshkey.DBSSHKey
	for _, key := range keys {
		dbKeys = append(dbKeys, &sshkey.DBSSHKey{
			Id:            uint64(key.ID),
			Name:          key.Name,
			Description:   key.Description,
			PublicKey:     key.PublicKey,
			KeyType:       key.KeyType,
			HasPassphrase: key.HasPassphraseSet(),
			CreatedAt:     key.CreatedAt.Format(timefmt.LayoutAPITime),
			UpdatedAt:     key.UpdatedAt.Format(timefmt.LayoutAPITime),
		})
	}

	response.Success(c, dbKeys)
}

// CreateDBSSHKey .
// @router /api/v1/system/db-ssh-keys [POST]
func CreateDBSSHKey(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c, func(req *sshkey.CreateDBSSHKeyRequest) (*sshkey.DBSSHKey, error) {
		if req.Name == "" {
			return nil, handler.ErrBadRequest("name is required")
		}

		sshKeyDAO := db.NewSSHKeyDAO()

		helper := git.NewSSHKeyHelper()
		publicKey := req.PublicKey
		keyType := "unknown"

		if req.PrivateKey != "" {
			keyType = helper.DetectKeyType(req.PrivateKey, req.Passphrase)
			if publicKey == "" {
				extractedKey, err := helper.ExtractPublicKeyFromPrivateKey(req.PrivateKey, req.Passphrase)
				if err != nil {
					return nil, handler.ErrBadRequest("failed to extract public key from private key: " + err.Error())
				}
				publicKey = extractedKey
			}
		} else if publicKey == "" {
			return nil, handler.ErrBadRequest("private_key is required when public_key is not provided")
		}

		exists, err := sshKeyDAO.ExistsByName(req.Name)
		if err != nil {
			return nil, handler.ErrInternal("Failed to check SSH key name: " + err.Error())
		}

		if exists {
			return nil, handler.ErrBadRequest("SSH key with this name already exists")
		}

		sshKey := &po.SSHKey{
			Name:        req.Name,
			Description: req.Description,
			PrivateKey:  req.PrivateKey,
			PublicKey:   publicKey,
			Passphrase:  req.Passphrase,
			KeyType:     keyType,
		}

		if err := sshKeyDAO.Create(sshKey); err != nil {
			return nil, handler.ErrInternal("Failed to create SSH key: " + err.Error())
		}

		return &sshkey.DBSSHKey{
			Id:            uint64(sshKey.ID),
			Name:          sshKey.Name,
			Description:   sshKey.Description,
			PublicKey:     sshKey.PublicKey,
			KeyType:       sshKey.KeyType,
			HasPassphrase: sshKey.HasPassphraseSet(),
			CreatedAt:     sshKey.CreatedAt.Format(timefmt.LayoutAPITime),
			UpdatedAt:     sshKey.UpdatedAt.Format(timefmt.LayoutAPITime),
		}, nil
	})
}

// GetDBSSHKey .
// @router /api/v1/system/db-ssh-keys/:id [GET]
func GetDBSSHKey(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c, func(req *sshkey.GetDBSSHKeyRequest) (*sshkey.DBSSHKey, error) {
		sshKeyDAO := db.NewSSHKeyDAO()
		key, err := sshKeyDAO.FindByID(uint(req.Id))
		if err != nil {
			return nil, handler.ErrNotFound("SSH key not found")
		}

		return &sshkey.DBSSHKey{
			Id:            uint64(key.ID),
			Name:          key.Name,
			Description:   key.Description,
			PublicKey:     key.PublicKey,
			KeyType:       key.KeyType,
			HasPassphrase: key.HasPassphraseSet(),
			CreatedAt:     key.CreatedAt.Format(timefmt.LayoutAPITime),
			UpdatedAt:     key.UpdatedAt.Format(timefmt.LayoutAPITime),
		}, nil
	})
}

// UpdateDBSSHKey .
// @router /api/v1/system/db-ssh-keys/:id [PUT]
func UpdateDBSSHKey(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c, func(req *sshkey.UpdateDBSSHKeyRequest) (*sshkey.DBSSHKey, error) {
		sshKeyDAO := db.NewSSHKeyDAO()
		key, err := sshKeyDAO.FindByID(uint(req.Id))
		if err != nil {
			return nil, handler.ErrNotFound("SSH key not found")
		}

		if req.Description != "" {
			key.Description = req.Description
		}

		// When the private key is changed, re-derive public key and key type
		if req.PrivateKey != "" {
			passphrase := req.Passphrase
			if passphrase == "" {
				passphrase = key.Passphrase
			}
			helper := git.NewSSHKeyHelper()
			newPublicKey, err := helper.ExtractPublicKeyFromPrivateKey(req.PrivateKey, passphrase)
			if err != nil {
				return nil, handler.ErrBadRequest("failed to extract public key from new private key: " + err.Error())
			}
			key.PrivateKey = req.PrivateKey
			key.PublicKey = newPublicKey
			key.KeyType = helper.DetectKeyType(req.PrivateKey, passphrase)
		}

		if req.Passphrase != "" {
			key.Passphrase = req.Passphrase
		}

		if err := sshKeyDAO.Update(key); err != nil {
			return nil, handler.ErrInternal("Failed to update SSH key: " + err.Error())
		}

		return &sshkey.DBSSHKey{
			Id:            uint64(key.ID),
			Name:          key.Name,
			Description:   key.Description,
			PublicKey:     key.PublicKey,
			KeyType:       key.KeyType,
			HasPassphrase: key.HasPassphraseSet(),
			CreatedAt:     key.CreatedAt.Format(timefmt.LayoutAPITime),
			UpdatedAt:     key.UpdatedAt.Format(timefmt.LayoutAPITime),
		}, nil
	})
}

// DeleteDBSSHKey .
// @router /api/v1/system/db-ssh-keys/:id [DELETE]
func DeleteDBSSHKey(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c, func(req *sshkey.DeleteDBSSHKeyRequest) (map[string]string, error) {
		sshKeyDAO := db.NewSSHKeyDAO()
		_, err := sshKeyDAO.FindByID(uint(req.Id))
		if err != nil {
			return nil, handler.ErrNotFound("SSH key not found")
		}

		if err := sshKeyDAO.Delete(uint(req.Id)); err != nil {
			return nil, handler.ErrInternal("Failed to delete SSH key: " + err.Error())
		}

		return map[string]string{
			"message": "SSH key deleted successfully",
		}, nil
	})
}

// TestDBSSHKey .
// @router /api/v1/system/db-ssh-keys/:id/test [POST]
func TestDBSSHKey(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c, func(req *sshkey.TestDBSSHKeyRequest) (map[string]interface{}, error) {
		if req.Url == "" {
			return nil, handler.ErrBadRequest("url is required")
		}

		sshKeyDAO := db.NewSSHKeyDAO()
		key, err := sshKeyDAO.FindByID(uint(req.Id))
		if err != nil {
			return nil, handler.ErrNotFound("SSH key not found")
		}

		gitSvc := git.NewGitService()
		err = gitSvc.TestRemoteConnectionWithDBKey(req.Url, key.PrivateKey, key.Passphrase)

		if err != nil {
			return map[string]interface{}{
				"success": false,
				"message": err.Error(),
			}, nil
		}

		return map[string]interface{}{
			"success": true,
			"message": "Connection successful",
		}, nil
	})
}
