// Code generated by hertz generator. DO NOT EDIT.

package sync

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	sync "github.com/yi-nology/git-manage-service/biz/handler/sync"
	syncv2 "github.com/yi-nology/git-manage-service/biz/handler/sync/v2"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {
	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			// V1 - Legacy
			_v1 := _api.Group("/v1", _v1Mw()...)
			{
				_sync := _v1.Group("/sync", _syncMw()...)
				_sync.POST("/analyze-repo", append(_analyzerepoforsyncMw(), sync.AnalyzeRepoForSync)...)
				_sync.POST("/batch", append(_batchsyncMw(), sync.BatchSync)...)
				_sync.POST("/execute", append(_executesyncMw(), sync.ExecuteSync)...)
				_sync.GET("/history", append(_listhistoryMw(), sync.ListHistory)...)
				_history := _sync.Group("/history", _historyMw()...)
				_history.POST("/delete", append(_deletehistoryMw(), sync.DeleteHistory)...)
				_sync.POST("/preview", append(_previewsyncMw(), sync.PreviewSync)...)
				_sync.POST("/run", append(_runtaskMw(), sync.RunTask)...)
				_sync.GET("/task", append(_gettaskMw(), sync.GetTask)...)
				_task := _sync.Group("/task", _taskMw()...)
				_task.POST("/create", append(_createtaskMw(), sync.CreateTask)...)
				_task.POST("/delete", append(_deletetaskMw(), sync.DeleteTask)...)
				_task.POST("/update", append(_updatetaskMw(), sync.UpdateTask)...)
				_sync.GET("/tasks", append(_listtasksMw(), sync.ListTasks)...)
			}

			// V2 - New git-sync-service based
			_v2 := _api.Group("/v2", _v1Mw()...)
			{
				_sync := _v2.Group("/sync", _syncMw()...)

				// Stats
				_sync.GET("/stats", syncv2.GetStats)

				// Tasks
				_sync.GET("/tasks", syncv2.ListTasks)
				_sync.GET("/task", syncv2.GetTask)
				_sync.POST("/task", syncv2.CreateTask)
				_sync.PUT("/task", syncv2.UpdateTask)
				_sync.DELETE("/task", syncv2.DeleteTask)
				_sync.POST("/task/run", syncv2.RunTask)
				_sync.POST("/tasks/batch-run", syncv2.BatchRunTasks)
				_sync.POST("/preview", syncv2.PreviewSync)

				// History
				_sync.GET("/history", syncv2.ListHistory)
				_sync.DELETE("/history", syncv2.DeleteHistory)

				// Webhook Rules
				_sync.GET("/webhook/rules", syncv2.ListRules)
				_sync.GET("/webhook/rule", syncv2.GetRule)
				_sync.POST("/webhook/rule", syncv2.CreateRule)
				_sync.PUT("/webhook/rule", syncv2.UpdateRule)
				_sync.DELETE("/webhook/rule", syncv2.DeleteRule)

				// Webhook Events
				_sync.GET("/webhook/events", syncv2.ListEvents)
				_sync.POST("/webhook/event/retry", syncv2.RetryEvent)
			}
		}
	}
}
