// Code generated by hertz generator.

package settings

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _branch_rulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _remote_configMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _provider_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ownerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getremoterepobranchrulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateremoterepobranchrulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _branch_rules0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbranchrulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _validatebranchnameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebranchrulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcodereviewsettingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecodereviewsettingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _llm_providersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listllmprovidersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletellmproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setdefaultllmproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testllmproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getllmproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatellmproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createllmproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}
