// Code generated by hertz generator.

package tag

import (
	"context"
	"strconv"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	tagModel "github.com/yi-nology/git-manage-service/biz/model/tag"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/handler"
)

// List .
// @router /api/v1/tag/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	handler.DoWithQueryRepo(c, func(repo *po.Repo) (any, error) {
		return git.NewGitService().GetTags(repo.Path)
	})
}

// Create .
// @router /api/v1/tag/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepo(c,
		func(r *tagModel.CreateTagRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *tagModel.CreateTagRequest) (any, error) {
			svc := git.NewGitService()
			authorName, authorEmail, _ := svc.GetGlobalGitUser()

			tagName := req.Name
			if tagName == "auto" {
				latest, err := svc.GetLatestVersion(repo.Path)
				if err != nil || latest == "" {
					tagName = "v0.1.0"
				} else {
					tagName = incrementVersion(latest)
				}
			}

			if err := svc.CreateTag(repo.Path, tagName, req.Ref, req.Message, authorName, authorEmail); err != nil {
				return nil, handler.ErrInternal("failed to create tag: " + err.Error())
			}

			if req.PushRemote != "" {
				if err := svc.PushTag(repo.Path, req.PushRemote, tagName, "none", "", ""); err != nil {
					return map[string]string{"status": "created_local_only", "error": "tag created but push failed: " + err.Error()}, nil
				}
			}
			return nil, nil
		},
	)
}

// Delete .
// @router /api/v1/tag/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepoVoid(c,
		func(r *tagModel.DeleteTagRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *tagModel.DeleteTagRequest) error {
			svc := git.NewGitService()
			if req.DeleteRemote && req.RemoteName != "" {
				if err := svc.DeleteRemoteTag(repo.Path, req.RemoteName, req.Name, "none", "", ""); err != nil {
					return handler.ErrInternal("failed to delete remote tag: " + err.Error())
				}
			}
			if err := svc.DeleteTag(repo.Path, req.Name); err != nil {
				return handler.ErrInternal("failed to delete local tag: " + err.Error())
			}
			return nil
		},
	)
}

// Push .
// @router /api/v1/tag/push [POST]
func Push(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepoVoid(c,
		func(r *tagModel.PushTagRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *tagModel.PushTagRequest) error {
			remote := req.RemoteName
			if remote == "" {
				remote = "origin"
			}
			if err := git.NewGitService().PushTag(repo.Path, remote, req.TagName, "none", "", ""); err != nil {
				return handler.ErrInternal("failed to push tag: " + err.Error())
			}
			return nil
		},
	)
}

func incrementVersion(v string) string {
	hasV := false
	if len(v) > 0 && v[0] == 'v' {
		hasV = true
		v = v[1:]
	}
	parts := strings.Split(v, ".")
	if len(parts) > 0 {
		lastIdx := len(parts) - 1
		lastNum, err := strconv.Atoi(parts[lastIdx])
		if err == nil {
			parts[lastIdx] = strconv.Itoa(lastNum + 1)
		} else {
			parts = append(parts, "1")
		}
	} else {
		return "v0.0.1"
	}
	res := strings.Join(parts, ".")
	if hasV {
		return "v" + res
	}
	return res
}
