// Code generated by hertz generator.

package review

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkmergeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _retrytaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _task_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfindingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tasks0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreviewconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatereviewconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _remote_configMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _provider_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ownerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getremoterepoconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateremoterepoconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpromptstructureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreviewstatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtasksbyproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtaskbyproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _findingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _finding_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreviewfeedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ragMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getragstatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _indexMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _indexreporagMw() []app.HandlerFunc {
	// your code...
	return nil
}
