// Code generated by hertz generator. DO NOT EDIT.

package review

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	review "github.com/yi-nology/git-manage-service/biz/handler/review"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			_v1.GET("/merge-checks", append(_checkmergeMw(), review.CheckMerge)...)
			{
				_review := _v1.Group("/review", _reviewMw()...)
				{
					_remote_config := _review.Group("/remote-config", _remote_configMw()...)
					{
						_provider_id := _remote_config.Group("/:provider_id", _provider_idMw()...)
						{
							_owner := _provider_id.Group("/:owner", _ownerMw()...)
							_owner.GET("/*repo", append(_getremoterepoconfigMw(), review.GetRemoteRepoConfig)...)
							_owner.PUT("/*repo", append(_updateremoterepoconfigMw(), review.UpdateRemoteRepoConfig)...)
						}
					}
				}
			}
			{
				_reviews := _v1.Group("/reviews", _reviewsMw()...)
				_reviews.GET("/audit-logs", append(_listauditlogsMw(), review.ListAuditLogs)...)
				_reviews.GET("/cli-configs", append(_listcliconfigsMw(), review.ListCLIConfigs)...)
				_cli_configs := _reviews.Group("/cli-configs", _cli_configsMw()...)
				_cli_configs.DELETE("/:id", append(_deletecliconfigMw(), review.DeleteCLIConfig)...)
				_id := _cli_configs.Group("/:id", _idMw()...)
				_id.POST("/test", append(_testcliconfigMw(), review.TestCLIConfig)...)
				_cli_configs.GET("/:id", append(_getcliconfigMw(), review.GetCLIConfig)...)
				_cli_configs.PUT("/:id", append(_updatecliconfigMw(), review.UpdateCLIConfig)...)
				_reviews.POST("/cli-configs", append(_createcliconfigMw(), review.CreateCLIConfig)...)
				_reviews.GET("/prompt-structure", append(_getpromptstructureMw(), review.GetPromptStructure)...)
				_reviews.GET("/stats", append(_getreviewstatsMw(), review.GetReviewStats)...)
				_reviews.GET("/tasks", append(_listtasksMw(), review.ListTasks)...)
				_tasks := _reviews.Group("/tasks", _tasksMw()...)
				_tasks.GET("/provider", append(_listtasksbyproviderMw(), review.ListTasksByProvider)...)
				_tasks.POST("/provider", append(_createtaskbyproviderMw(), review.CreateTaskByProvider)...)
				{
					_id0 := _tasks.Group("/:id", _id0Mw()...)
					_id0.POST("/retry", append(_retrytaskMw(), review.RetryTask)...)
				}
				{
					_task_id := _tasks.Group("/:task_id", _task_idMw()...)
					_task_id.GET("/findings", append(_listfindingsMw(), review.ListFindings)...)
				}
				_reviews.POST("/tasks", append(_createtaskMw(), review.CreateTask)...)
				_tasks0 := _reviews.Group("/tasks", _tasks0Mw()...)
				_tasks0.GET("/:id", append(_gettaskMw(), review.GetTask)...)
				{
					_config := _reviews.Group("/config", _configMw()...)
					_config.GET("/:repo_key", append(_getreviewconfigMw(), review.GetReviewConfig)...)
					_config.PUT("/:repo_key", append(_updatereviewconfigMw(), review.UpdateReviewConfig)...)
				}
				{
					_findings := _reviews.Group("/findings", _findingsMw()...)
					{
						_finding_id := _findings.Group("/:finding_id", _finding_idMw()...)
						_finding_id.POST("/feedback", append(_getreviewfeedbackMw(), review.GetReviewFeedback)...)
					}
				}
				{
					_rag := _reviews.Group("/rag", _ragMw()...)
					_rag.GET("/stats", append(_getragstatsMw(), review.GetRAGStats)...)
					{
						_index := _rag.Group("/index", _indexMw()...)
						_index.POST("/:repo_key", append(_indexreporagMw(), review.IndexRepoRAG)...)
					}
				}
			}
		}
	}
}
