// Code generated by hertz generator. DO NOT EDIT.

package ai

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	ai "github.com/yi-nology/git-manage-service/biz/handler/ai"
)

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			{
				_ai := _v1.Group("/ai", _aiMw()...)
				_ai.POST("/audit/summary", append(_summarizeauditlogsMw(), ai.SummarizeAuditLogs)...)
				_ai.POST("/branch/rule", append(_generatebranchruleMw(), ai.GenerateBranchRule)...)
				_ai.POST("/commit/message", append(_generatecommitmessageMw(), ai.GenerateCommitMessage)...)
				_ai.POST("/conflict/explain", append(_explainconflictMw(), ai.ExplainConflict)...)
				_ai.POST("/conflict/resolve", append(_resolveconflictMw(), ai.ResolveConflict)...)
				_ai.POST("/patch/analyze", append(_analyzepatchriskMw(), ai.AnalyzePatchRisk)...)
				_ai.POST("/provider/binding", append(_recommendproviderbindingMw(), ai.RecommendProviderBinding)...)
				_ai.POST("/repo/summary", append(_generatereposummaryMw(), ai.GenerateRepoSummary)...)
				_ai.POST("/review", append(_codereviewMw(), ai.CodeReview)...)
				_ai.POST("/review/reply", append(_reviewreplydraftMw(), ai.ReviewReplyDraft)...)
				_ai.POST("/review/summary", ai.ReviewSummary)
				_ai.POST("/spec/rewrite", append(_rewritespecsectionMw(), ai.RewriteSpecSection)...)
				_ai.POST("/spec/template", append(_generatespectemplateMw(), ai.GenerateSpecTemplate)...)
				_ai.POST("/stats/insight", append(_analyzestatsinsightMw(), ai.AnalyzeStatsInsight)...)
				_ai.POST("/sync/failure", append(_diagnosesyncfailureMw(), ai.DiagnoseSyncFailure)...)
 				_ai.POST("/webhook/failure", append(_analyzewebhookfailureMw(), ai.AnalyzeWebhookFailure)...)
 				_ai.POST("/feedback", ai.SubmitUserFeedback)
 			}
 		}
 	}
 }
