// Code generated by hertz generator.

package author

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _identitiesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listidentitiesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteidentityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activateidentityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateidentityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createidentityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repo_keyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _author0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrepoauthorconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setrepoauthorconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fixauthorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fixauthorallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _scanauthorMw() []app.HandlerFunc {
	// your code...
	return nil
}
