// Code generated by hertz generator.

package webhook

import (
	"bytes"
	"context"
	"io"
	"log"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/google/uuid"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	webhook "github.com/yi-nology/git-manage-service/biz/model/webhook"
	"github.com/yi-nology/git-manage-service/biz/service/provider_manager"
	syncv2 "github.com/yi-nology/git-manage-service/biz/service/sync/v2"
	"github.com/yi-nology/git-manage-service/biz/service/webhookevent"
	"github.com/yi-nology/git-manage-service/pkg/handler"
	"github.com/yi-nology/git-manage-service/pkg/response"
	"github.com/yi-nology/git-platform-sdk/provider"
)

// TriggerSync .
// @router /api/webhooks/task-sync [POST]
func TriggerSync(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c, func(req *webhook.TriggerSyncRequest) (map[string]interface{}, error) {
		// 支持task_key或task_id
		taskKey := req.TaskKey
		if taskKey == "" {
			taskKey = req.TaskId
		}
		if taskKey == "" {
			return nil, handler.ErrBadRequest("task_key or task_id is required")
		}

		// 查找任务
		svc := syncv2.GetService()
		task, err := svc.GetTask(ctx, taskKey)
		if err != nil {
			return nil, handler.ErrNotFound("task not found")
		}

		// 生成执行ID
		runID := uuid.New().String()

		// 异步执行同步任务
		go func() {
			if err := svc.RunTask(context.Background(), task.Key); err != nil {
				log.Printf("[sync] async RunTask %s failed: %v", task.Key, err)
			}
		}()

		c.Set("audit_target", "task:"+task.Key)
		c.Set("audit_details", map[string]string{"task_key": taskKey})
		return map[string]interface{}{
			"run_id":   runID,
			"task_key": task.Key,
			"status":   "started",
			"message":  "sync task triggered",
		}, nil
	})
}

// TriggerSyncByToken .
// @router /api/webhooks/trigger/:token [POST]
func TriggerSyncByToken(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c, func(req *webhook.TriggerSyncByTokenRequest) (map[string]interface{}, error) {
		token := req.Token
		if token == "" {
			token = c.Param("token")
		}
		if token == "" {
			return nil, handler.ErrBadRequest("token is required")
		}

		// 通过 token 查找任务（git-sync-service 是任务的真正来源）
		svc := syncv2.GetService()
		task, err := svc.FindTaskByWebhookToken(ctx, token)
		if err != nil || task == nil {
			return nil, handler.ErrNotFound("task not found for this token")
		}

		// 生成执行ID
		runID := uuid.New().String()

		// 异步执行同步任务
		go func() {
			if err := svc.RunTask(context.Background(), task.Key); err != nil {
				log.Printf("[sync] async RunTask %s failed: %v", task.Key, err)
			}
		}()

		c.Set("audit_target", "task:"+task.Key)
		return map[string]interface{}{
			"run_id":   runID,
			"task_key": task.Key,
			"status":   "started",
			"message":  "sync task triggered by token",
		}, nil
	})
}

func Receive(ctx context.Context, c *app.RequestContext) {
	cfgDAO := db.NewProviderConfigDAO()
	configs, err := cfgDAO.FindAll()
	if err != nil || len(configs) == 0 {
		response.BadRequest(c, "No provider configs found")
		return
	}

	var matchedProvider provider.WebhookManager
	var matchedCfg po.ProviderConfig
	for _, cfg := range configs {
		p, pErr := provider_manager.GetManager().GetProvider(cfg.ID)
		if pErr != nil {
			continue
		}
		stdReq := toHTTPRequest(c)
		if validateErr := p.ValidateWebhookSignature(stdReq, cfg.WebhookSecret); validateErr == nil {
			matchedProvider = p
			matchedCfg = cfg
			break
		}
	}

	if matchedProvider == nil {
		response.BadRequest(c, "Could not identify webhook source")
		return
	}

	event, err := matchedProvider.ParseWebhookEvent(toHTTPRequest(c), matchedCfg.WebhookSecret)
	if err != nil {
		response.BadRequest(c, "Failed to parse webhook: "+err.Error())
		return
	}

	go func() {
		if processErr := webhookevent.ProcessIncomingEvent(event, matchedCfg.ID); processErr != nil {
			_ = processErr
		}
	}()

	body, _ := c.Body()
	c.Set("audit_target", string(body))
	response.Accepted(c, "Webhook received", map[string]interface{}{
		"event_id":   event.ID,
		"event_type": event.Type,
		"source":     string(event.Source),
	})
}

func toHTTPRequest(c *app.RequestContext) *http.Request {
	body, _ := c.Body()
	req, _ := http.NewRequest(string(c.Request.Header.Method()), c.Request.URI().String(), bytes.NewReader(body))
	c.Request.Header.VisitAll(func(key, value []byte) {
		req.Header.Set(string(key), string(value))
	})
	req.Body = io.NopCloser(bytes.NewReader(body))
	return req
}
