// Code generated by hertz generator.

package branch

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	branch "github.com/yi-nology/git-manage-service/biz/model/branch"
	common "github.com/yi-nology/git-manage-service/biz/model/common"
)

// List .
// @router /api/v1/branch/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.ListBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.ListBranchResponse)

	c.JSON(consts.StatusOK, resp)
}

// Create .
// @router /api/v1/branch/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.CreateBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// Delete .
// @router /api/v1/branch/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.DeleteBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// Update .
// @router /api/v1/branch/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.UpdateBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// Checkout .
// @router /api/v1/branch/checkout [POST]
func Checkout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.CheckoutBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// Push .
// @router /api/v1/branch/push [POST]
func Push(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.PushBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// Pull .
// @router /api/v1/branch/pull [POST]
func Pull(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.PullBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// Compare .
// @router /api/v1/branch/compare [GET]
func Compare(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.CompareBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.CompareBranchResponse)

	c.JSON(consts.StatusOK, resp)
}

// Merge .
// @router /api/v1/branch/merge [POST]
func Merge(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.MergeBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.MergeBranchResponse)

	c.JSON(consts.StatusOK, resp)
}

// MergeCheck .
// @router /api/v1/branch/merge/check [GET]
func MergeCheck(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.MergeCheckRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.MergeCheckResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetDiff .
// @router /api/v1/branch/diff [GET]
func GetDiff(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.GetDiffRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.GetDiffResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetPatch .
// @router /api/v1/branch/patch [GET]
func GetPatch(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.GetPatchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.GetPatchResponse)

	c.JSON(consts.StatusOK, resp)
}

// CherryPick .
// @router /api/v1/branch/cherry-pick [POST]
func CherryPick(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.CherryPickRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.CherryPickResponse)

	c.JSON(consts.StatusOK, resp)
}

// Rebase .
// @router /api/v1/branch/rebase [POST]
func Rebase(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.RebaseRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.RebaseResponse)

	c.JSON(consts.StatusOK, resp)
}

// RebaseAbort .
// @router /api/v1/branch/rebase/abort [POST]
func RebaseAbort(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.RebaseAbortRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// RebaseContinue .
// @router /api/v1/branch/rebase/continue [POST]
func RebaseContinue(ctx context.Context, c *app.RequestContext) {
	var err error
	var req branch.RebaseContinueRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(branch.RebaseResponse)

	c.JSON(consts.StatusOK, resp)
}
