// Code generated by hertz generator.

package webhook_event

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _webhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _retryMw() []app.HandlerFunc {
	// your code...
	return nil
}
