// Code generated by hertz generator.

package file

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	file "github.com/yi-nology/git-manage-service/biz/model/file"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/handler"
)

// GetTree .
// @router /api/v1/file/tree [GET]
func GetTree(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepo(c,
		func(r *file.GetTreeRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *file.GetTreeRequest) (any, error) {
			svc := git.NewGitService()
			ref := req.Ref
			if ref == "" {
				ref = "HEAD"
			}

			if ref == "worktree" {
				entries, err := svc.GetWorktree(repo.Path, req.Path)
				if err != nil {
					return nil, err
				}
				return buildTreeResponse(entries, "worktree", req.Path), nil
			}

			entries, err := svc.GetTree(repo.Path, ref, req.Path, req.Recursive)
			if err != nil {
				return nil, err
			}
			return buildTreeResponse(entries, ref, req.Path), nil
		},
	)
}

func buildTreeResponse(entries []git.TreeEntry, ref, path string) map[string]interface{} {
	var treeEntries []*file.TreeEntry
	for _, e := range entries {
		treeEntries = append(treeEntries, &file.TreeEntry{
			Name: e.Name, Path: e.Path, Type: e.Type,
			Size: e.Size, Mode: e.Mode, Hash: e.Hash,
		})
	}
	return map[string]interface{}{"entries": treeEntries, "current_ref": ref, "current_path": path}
}

// GetBlob .
// @router /api/v1/file/blob [GET]
func GetBlob(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepo(c,
		func(r *file.GetBlobRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *file.GetBlobRequest) (any, error) {
			svc := git.NewGitService()
			ref := req.Ref
			if ref == "" {
				ref = "HEAD"
			}

			if ref == "worktree" {
				blob, err := svc.GetWorktreeBlob(repo.Path, req.Path)
				if err != nil {
					return nil, err
				}
				return blobResponse(blob), nil
			}
			blob, err := svc.GetBlob(repo.Path, ref, req.Path)
			if err != nil {
				return nil, err
			}
			return blobResponse(blob), nil
		},
	)
}

func blobResponse(b *git.BlobContent) map[string]interface{} {
	return map[string]interface{}{
		"content": b.Content, "encoding": b.Encoding,
		"size": b.Size, "is_binary": b.IsBinary, "mime_type": b.MimeType,
	}
}

// GetFileHistory .
// @router /api/v1/file/history [GET]
func GetFileHistory(ctx context.Context, c *app.RequestContext) {
	handler.DoWithRepo(c,
		func(r *file.GetFileHistoryRequest) string { return r.RepoKey },
		func(repo *po.Repo, req *file.GetFileHistoryRequest) (any, error) {
			ref := req.Ref
			if ref == "" {
				ref = "HEAD"
			}
			limit := int(req.Limit)
			if limit <= 0 {
				limit = 50
			}
			commits, err := git.NewGitService().GetFileHistory(repo.Path, ref, req.Path, limit)
			if err != nil {
				return nil, err
			}
			var fcs []*file.FileCommit
			for _, cm := range commits {
				fcs = append(fcs, &file.FileCommit{
					Hash: cm.Hash, ShortHash: cm.ShortHash,
					Message: cm.Message, Author: cm.Author, Date: cm.Date,
				})
			}
			return map[string]interface{}{"commits": fcs}, nil
		},
	)
}
