// Code generated by hertz generator.

package provider

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	common "github.com/yi-nology/git-manage-service/biz/model/common"
	provider "github.com/yi-nology/git-manage-service/biz/model/provider"
)

// List .
// @router /api/v1/providers [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.ListProvidersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(provider.ListProvidersResponse)

	c.JSON(consts.StatusOK, resp)
}

// Get .
// @router /api/v1/providers/:id [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.GetProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(provider.ProviderResponse)

	c.JSON(consts.StatusOK, resp)
}

// Create .
// @router /api/v1/providers [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.CreateProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(provider.ProviderResponse)

	c.JSON(consts.StatusOK, resp)
}

// Update .
// @router /api/v1/providers/:id [PUT]
func Update(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.UpdateProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(provider.ProviderResponse)

	c.JSON(consts.StatusOK, resp)
}

// Delete .
// @router /api/v1/providers/:id [DELETE]
func Delete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.DeleteProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// Test .
// @router /api/v1/providers/:id/test [POST]
func Test(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.TestProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(provider.TestProviderResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListRemoteRepos .
// @router /api/v1/providers/:id/repos [GET]
func ListRemoteRepos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.ListRemoteReposRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(provider.ListRemoteReposResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListRemoteBranches .
// @router /api/v1/providers/branches [GET]
func ListRemoteBranches(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.ListRemoteBranchesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(provider.ListRemoteBranchesResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateRemoteBranch .
// @router /api/v1/providers/branches/create [POST]
func CreateRemoteBranch(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.CreateRemoteBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(provider.CreateRemoteBranchResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteRemoteBranch .
// @router /api/v1/providers/branches/delete [POST]
func DeleteRemoteBranch(ctx context.Context, c *app.RequestContext) {
	var err error
	var req provider.DeleteRemoteBranchRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}
