// Code generated by hertz generator.

package binding

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bindingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _autodetectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setprimaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletewebhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerwebhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}
