// Code generated by hertz generator.

package binding

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	binding "github.com/yi-nology/git-manage-service/biz/model/binding"
	common "github.com/yi-nology/git-manage-service/biz/model/common"
)

// List .
// @router /api/v1/bindings [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.ListBindingsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(binding.ListBindingsResponse)

	c.JSON(consts.StatusOK, resp)
}

// Get .
// @router /api/v1/bindings/:id [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.GetBindingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(binding.BindingResponse)

	c.JSON(consts.StatusOK, resp)
}

// Create .
// @router /api/v1/bindings [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.CreateBindingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(binding.BindingResponse)

	c.JSON(consts.StatusOK, resp)
}

// Update .
// @router /api/v1/bindings/:id [PUT]
func Update(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.UpdateBindingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(binding.BindingResponse)

	c.JSON(consts.StatusOK, resp)
}

// Delete .
// @router /api/v1/bindings/:id [DELETE]
func Delete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.DeleteBindingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// SetPrimary .
// @router /api/v1/bindings/:id/set-primary [POST]
func SetPrimary(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.SetPrimaryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(binding.BindingResponse)

	c.JSON(consts.StatusOK, resp)
}

// AutoDetect .
// @router /api/v1/bindings/auto-detect [POST]
func AutoDetect(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.AutoDetectRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(binding.AutoDetectResponse)

	c.JSON(consts.StatusOK, resp)
}

// RegisterWebhook .
// @router /api/v1/bindings/:id/webhook [POST]
func RegisterWebhook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.WebhookRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteWebhook .
// @router /api/v1/bindings/:id/webhook [DELETE]
func DeleteWebhook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req binding.WebhookRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}
