// Code generated by hertz generator.

package audit

import (
	"context"
	"fmt"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	auditModel "github.com/yi-nology/git-manage-service/biz/model/audit"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	"github.com/yi-nology/git-manage-service/pkg/handler"
	"github.com/yi-nology/git-manage-service/pkg/response"
)

// List .
// @router /api/v1/audit/logs [GET]
func List(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c, func(req *auditModel.ListAuditLogRequest) (map[string]interface{}, error) {
		page := int(req.Page)
		if page < 1 {
			page = 1
		}
		pageSize := int(req.PageSize)
		if pageSize < 1 {
			pageSize = 20
		}

		dao := db.NewAuditLogDAO()
		logs, err := dao.FindPageWithFilters(page, pageSize, req.Action, req.Target, req.StartDate, req.EndDate)
		if err != nil {
			return nil, handler.ErrInternal(err.Error())
		}

		total, _ := dao.CountWithFilters(req.Action, req.Target, req.StartDate, req.EndDate)

		dtos := make([]*auditModel.AuditLog, len(logs))
		for i, log := range logs {
			dtos[i] = convertToProtoAuditLog(&log)
		}

		return map[string]interface{}{
			"items": dtos,
			"total": total,
			"page":  page,
			"size":  pageSize,
		}, nil
	})
}

// Get .
// @router /api/v1/audit/log [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	idStr := c.Query("id")
	if idStr == "" {
		response.BadRequest(c, "id is required")
		return
	}

	id, err := strconv.Atoi(idStr)
	if err != nil {
		response.BadRequest(c, "invalid id")
		return
	}

	log, err := db.NewAuditLogDAO().FindByID(uint(id))
	if err != nil {
		response.NotFound(c, "audit log not found")
		return
	}

	response.Success(c, convertToProtoAuditLog(log))
}

func convertToProtoAuditLog(l *po.AuditLog) *auditModel.AuditLog {
	return &auditModel.AuditLog{
		Id:        int64(l.ID),
		Action:    l.Action,
		Target:    l.Target,
		Detail:    l.Details,
		Operator:  l.Operator,
		Ip:        l.IPAddress,
		UserAgent: l.UserAgent,
		CreatedAt: fmt.Sprintf("%d", l.CreatedAt.Unix()),
	}
}
