// Code generated by hertz generator.

package version

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/model/po"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/handler"
)

// GetVersion .
// @router /api/v1/version/current [GET]
func GetVersion(ctx context.Context, c *app.RequestContext) {
	handler.DoWithQueryRepo(c, func(repo *po.Repo) (interface{}, error) {
		version, err := git.NewGitService().GetDescribe(repo.Path)
		if err != nil {
			return nil, handler.ErrInternal("failed to determine version: " + err.Error())
		}
		return version, nil
	})
}

// ListVersions .
// @router /api/v1/version/list [GET]
func ListVersions(ctx context.Context, c *app.RequestContext) {
	handler.DoWithQueryRepo(c, func(repo *po.Repo) (interface{}, error) {
		tags, err := git.NewGitService().GetTagList(repo.Path)
		if err != nil {
			return nil, handler.ErrInternal(err.Error())
		}
		return tags, nil
	})
}

// GetNextVersions .
// @router /api/v1/version/next [GET]
func GetNextVersions(ctx context.Context, c *app.RequestContext) {
	handler.DoWithQueryRepo(c, func(repo *po.Repo) (interface{}, error) {
		info, err := git.NewGitService().GetNextVersions(repo.Path)
		if err != nil {
			return nil, handler.ErrInternal("failed to calculate next versions: " + err.Error())
		}
		return info, nil
	})
}
