// Code generated by hertz generator.

package spec

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	common "github.com/yi-nology/git-manage-service/biz/model/common"
	spec "github.com/yi-nology/git-manage-service/biz/model/spec"
)

// GetSpecTree .
// @router /api/v1/spec/tree [GET]
func GetSpecTree(ctx context.Context, c *app.RequestContext) {
	var err error
	var req common.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.SpecTreeResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListSpecFiles .
// @router /api/v1/spec/list [GET]
func ListSpecFiles(ctx context.Context, c *app.RequestContext) {
	var err error
	var req common.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.SpecFileListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetSpecContent .
// @router /api/v1/spec/content [GET]
func GetSpecContent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.SpecContentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.SpecContentResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetSpecContentByPath .
// @router /api/v1/spec/content/:path [GET]
func GetSpecContentByPath(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.SpecContentByPathRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.SpecContentResponse)

	c.JSON(consts.StatusOK, resp)
}

// SaveSpecContent .
// @router /api/v1/spec/save [POST]
func SaveSpecContent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.SaveSpecContentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// SaveSpecContentByPath .
// @router /api/v1/spec/content/:path [PUT]
func SaveSpecContentByPath(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.SaveSpecContentByPathRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// LintSpec .
// @router /api/v1/spec/lint [POST]
func LintSpec(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.LintRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.LintResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetLintRules .
// @router /api/v1/spec/rules [GET]
func GetLintRules(ctx context.Context, c *app.RequestContext) {
	var err error
	var req common.EmptyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.LintRuleListResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateLintRule .
// @router /api/v1/spec/rules/:id [PUT]
func UpdateLintRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.UpdateLintRuleRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.LintRuleResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateLintRule .
// @router /api/v1/spec/rules [POST]
func CreateLintRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.CreateLintRuleRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.LintRuleResponse)

	c.JSON(consts.StatusOK, resp)
}

// CommitSpec .
// @router /api/v1/spec/commit/:path [POST]
func CommitSpec(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.CommitSpecRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// ValidateSpec .
// @router /api/v1/spec/validate [POST]
func ValidateSpec(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.ValidateSpecRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.ValidateSpecResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateSpecFile .
// @router /api/v1/spec/create [POST]
func CreateSpecFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.CreateSpecFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteSpecFile .
// @router /api/v1/spec/delete [POST]
func DeleteSpecFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.DeleteSpecFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// AIAssistSpec .
// @router /api/v1/spec/ai-assist [POST]
func AIAssistSpec(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.AIAssistRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.AIAssistResponse)

	c.JSON(consts.StatusOK, resp)
}

// AIFixSpec .
// @router /api/v1/spec/ai-fix [POST]
func AIFixSpec(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.AIFixRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.AIFixResponse)

	c.JSON(consts.StatusOK, resp)
}

// FormatSpec .
// @router /api/v1/spec/format [POST]
func FormatSpec(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.FormatSpecRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.FormatSpecResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetSpecConfig .
// @router /api/v1/spec/config [GET]
func GetSpecConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.GetSpecConfigRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.SpecConfigResponse)

	c.JSON(consts.StatusOK, resp)
}

// SaveSpecConfig .
// @router /api/v1/spec/config [PUT]
func SaveSpecConfig(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spec.SaveSpecConfigRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(spec.SpecConfigResponse)

	c.JSON(consts.StatusOK, resp)
}
