// Code generated by hertz generator.

package cr

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _crMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _closeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mergeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _remoteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _closebyproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbyproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listbyproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mergebyproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}
