// Code generated by hertz generator.

package cr

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	cr "github.com/yi-nology/git-manage-service/biz/model/cr"
)

// Create .
// @router /api/v1/cr/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.CreateCRRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.CRResponse)

	c.JSON(consts.StatusOK, resp)
}

// Get .
// @router /api/v1/cr/detail [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.GetCRRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.CRResponse)

	c.JSON(consts.StatusOK, resp)
}

// List .
// @router /api/v1/cr/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.ListCRsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.ListCRsResponse)

	c.JSON(consts.StatusOK, resp)
}

// Merge .
// @router /api/v1/cr/merge [POST]
func Merge(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.MergeCRRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.CRResponse)

	c.JSON(consts.StatusOK, resp)
}

// Close .
// @router /api/v1/cr/close [POST]
func Close(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.CloseCRRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.CRResponse)

	c.JSON(consts.StatusOK, resp)
}

// Sync .
// @router /api/v1/cr/sync [POST]
func Sync(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.SyncCRsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.SyncCRsResponse)

	c.JSON(consts.StatusOK, resp)
}

// Detect .
// @router /api/v1/cr/detect [GET]
func Detect(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.DetectCRRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.DetectCRResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListByProvider .
// @router /api/v1/cr/remote/list [GET]
func ListByProvider(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.ListCRsByProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.ListCRsResponse)

	c.JSON(consts.StatusOK, resp)
}

// CreateByProvider .
// @router /api/v1/cr/remote/create [POST]
func CreateByProvider(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.CreateCRByProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.CRResponse)

	c.JSON(consts.StatusOK, resp)
}

// MergeByProvider .
// @router /api/v1/cr/remote/merge [POST]
func MergeByProvider(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.MergeCRByProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.CRResponse)

	c.JSON(consts.StatusOK, resp)
}

// CloseByProvider .
// @router /api/v1/cr/remote/close [POST]
func CloseByProvider(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cr.CloseCRByProviderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(cr.CRResponse)

	c.JSON(consts.StatusOK, resp)
}
