// Code generated by hertz generator.

package ai

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ai "github.com/yi-nology/git-manage-service/biz/model/ai"
)

// DiagnoseSyncFailure .
// @router /api/v1/ai/sync/failure [POST]
func DiagnoseSyncFailure(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.SyncFailureRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDiagnosisResponse)

	c.JSON(consts.StatusOK, resp)
}

// GenerateRepoSummary .
// @router /api/v1/ai/repo/summary [POST]
func GenerateRepoSummary(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.RepoSummaryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIAdviceResponse)

	c.JSON(consts.StatusOK, resp)
}

// GenerateCommitMessage .
// @router /api/v1/ai/commit/message [POST]
func GenerateCommitMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.CommitMessageRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDraftResponse)

	c.JSON(consts.StatusOK, resp)
}

// CodeReview .
// @router /api/v1/ai/review [POST]
func CodeReview(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.CodeReviewRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIReviewResponse)

	c.JSON(consts.StatusOK, resp)
}

// ReviewReplyDraft .
// @router /api/v1/ai/review/reply [POST]
func ReviewReplyDraft(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ReviewReplyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDraftResponse)

	c.JSON(consts.StatusOK, resp)
}

// ResolveConflict .
// @router /api/v1/ai/conflict/resolve [POST]
func ResolveConflict(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ConflictResolveRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDraftResponse)

	c.JSON(consts.StatusOK, resp)
}

// ExplainConflict .
// @router /api/v1/ai/conflict/explain [POST]
func ExplainConflict(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ConflictResolveRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIAdviceResponse)

	c.JSON(consts.StatusOK, resp)
}

// GenerateBranchRule .
// @router /api/v1/ai/branch/rule [POST]
func GenerateBranchRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.BranchRuleRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDraftResponse)

	c.JSON(consts.StatusOK, resp)
}

// GenerateSpecTemplate .
// @router /api/v1/ai/spec/template [POST]
func GenerateSpecTemplate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.SpecTemplateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDraftResponse)

	c.JSON(consts.StatusOK, resp)
}

// RewriteSpecSection .
// @router /api/v1/ai/spec/rewrite [POST]
func RewriteSpecSection(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.SpecRewriteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDraftResponse)

	c.JSON(consts.StatusOK, resp)
}

// RecommendProviderBinding .
// @router /api/v1/ai/provider/binding [POST]
func RecommendProviderBinding(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.ProviderBindingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIAdviceResponse)

	c.JSON(consts.StatusOK, resp)
}

// AnalyzePatchRisk .
// @router /api/v1/ai/patch/analyze [POST]
func AnalyzePatchRisk(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.PatchAnalysisRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDiagnosisResponse)

	c.JSON(consts.StatusOK, resp)
}

// SummarizeAuditLogs .
// @router /api/v1/ai/audit/summary [POST]
func SummarizeAuditLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.AuditSummaryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIAdviceResponse)

	c.JSON(consts.StatusOK, resp)
}

// AnalyzeStatsInsight .
// @router /api/v1/ai/stats/insight [POST]
func AnalyzeStatsInsight(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.StatsInsightRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIAdviceResponse)

	c.JSON(consts.StatusOK, resp)
}

// AnalyzeWebhookFailure .
// @router /api/v1/ai/webhook/failure [POST]
func AnalyzeWebhookFailure(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ai.WebhookFailureRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ai.AIDiagnosisResponse)

	c.JSON(consts.StatusOK, resp)
}
