// Code generated by hertz generator.

package maintenance

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repo_keyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _maintenanceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gcMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gitignoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _slimMw() []app.HandlerFunc {
	// your code...
	return nil
}
