// Code generated by hertz generator.

package repo

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	common "github.com/yi-nology/git-manage-service/biz/model/common"
	repo "github.com/yi-nology/git-manage-service/biz/model/repo"
)

// List .
// @router /api/v1/repo/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.ListRepoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.ListRepoResponse)

	c.JSON(consts.StatusOK, resp)
}

// Get .
// @router /api/v1/repo/detail [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.GetRepoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.RepoResponse)

	c.JSON(consts.StatusOK, resp)
}

// Create .
// @router /api/v1/repo/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.CreateRepoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.RepoResponse)

	c.JSON(consts.StatusOK, resp)
}

// Update .
// @router /api/v1/repo/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.UpdateRepoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.RepoResponse)

	c.JSON(consts.StatusOK, resp)
}

// Delete .
// @router /api/v1/repo/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.DeleteRepoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// Scan .
// @router /api/v1/repo/scan [POST]
func Scan(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.ScanRepoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.ScanRepoResponse)

	c.JSON(consts.StatusOK, resp)
}

// Clone .
// @router /api/v1/repo/clone [POST]
func Clone(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.CloneRepoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.CloneRepoResponse)

	c.JSON(consts.StatusOK, resp)
}

// Fetch .
// @router /api/v1/repo/fetch [POST]
func Fetch(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.FetchRepoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.EmptyResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetCloneTask .
// @router /api/v1/repo/task [GET]
func GetCloneTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.GetCloneTaskRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.CloneTaskResponse)

	c.JSON(consts.StatusOK, resp)
}

// ScanDirectory .
// @router /api/v1/repo/scan-directory [POST]
func ScanDirectory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.ScanDirectoryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.ScanDirectoryResponse)

	c.JSON(consts.StatusOK, resp)
}

// BatchCreate .
// @router /api/v1/repo/batch-create [POST]
func BatchCreate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.BatchCreateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(repo.BatchCreateResponse)

	c.JSON(consts.StatusOK, resp)
}
