// Code generated by hertz generator.

package system

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/git-manage-service/biz/dal/db"
	systemModel "github.com/yi-nology/git-manage-service/biz/model/system"
	"github.com/yi-nology/git-manage-service/biz/service/auth"
	"github.com/yi-nology/git-manage-service/biz/service/git"
	"github.com/yi-nology/git-manage-service/pkg/appinfo"
	"github.com/yi-nology/git-manage-service/pkg/configs"
	"github.com/yi-nology/git-manage-service/pkg/handler"
	"github.com/yi-nology/git-manage-service/pkg/response"
	"github.com/yi-nology/git-platform-sdk/gitbackend"
)

// GetConfig .
// @router /api/v1/system/config [GET]
func GetConfig(ctx context.Context, c *app.RequestContext) {
	gitSvc := git.NewGitService()
	name, email, _ := gitSvc.GetGlobalGitUser()

	response.Success(c, map[string]interface{}{
		"debug_mode":   configs.DebugMode,
		"author_name":  name,
		"author_email": email,
	})
}

// UpdateConfig .
// @router /api/v1/system/config [POST]
func UpdateConfig(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c,
		func(req *systemModel.UpdateConfigRequest) (map[string]interface{}, error) {
			configs.DebugMode = req.DebugMode

			gitSvc := git.NewGitService()
			if err := gitSvc.SetGlobalGitUser(req.AuthorName, req.AuthorEmail); err != nil {
				return nil, handler.ErrInternal("Failed to set git config: " + err.Error())
			}

			return map[string]interface{}{
				"debug_mode":   configs.DebugMode,
				"author_name":  req.AuthorName,
				"author_email": req.AuthorEmail,
			}, nil
		},
	)
}

// ListDirs .
// @router /api/v1/system/dirs [GET]
func ListDirs(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c,
		func(req *systemModel.ListDirsRequest) (map[string]interface{}, error) {
			currentPath := req.Path
			if currentPath == "" {
				home, err := os.UserHomeDir()
				if err != nil {
					currentPath = "/"
				} else {
					currentPath = home
				}
			}

			entries, err := os.ReadDir(currentPath)
			if err != nil {
				return nil, handler.ErrInternal(err.Error())
			}

			var dirs []*systemModel.DirEntry
			for _, entry := range entries {
				if entry.IsDir() && !strings.HasPrefix(entry.Name(), ".") {
					if req.Search != "" && !strings.Contains(strings.ToLower(entry.Name()), strings.ToLower(req.Search)) {
						continue
					}
					dirs = append(dirs, &systemModel.DirEntry{
						Name:  entry.Name(),
						Path:  filepath.Join(currentPath, entry.Name()),
						IsDir: true,
					})
				}
			}

			slices.SortFunc(dirs, func(a, b *systemModel.DirEntry) int {
				return strings.Compare(a.Name, b.Name)
			})

			parent := filepath.Dir(currentPath)
			if currentPath == "/" {
				parent = ""
			}

			return map[string]interface{}{
				"parent":  parent,
				"current": currentPath,
				"dirs":    dirs,
			}, nil
		},
	)
}

// ListSSHKeys .
// @router /api/v1/system/ssh-keys [GET]
func ListSSHKeys(ctx context.Context, c *app.RequestContext) {
	home, err := os.UserHomeDir()
	if err != nil {
		response.InternalServerError(c, "cannot find home dir")
		return
	}

	sshDir := filepath.Join(home, ".ssh")
	entries, err := os.ReadDir(sshDir)
	if err != nil {
		response.Success(c, []*systemModel.SSHKey{})
		return
	}

	var keys []*systemModel.SSHKey
	for _, entry := range entries {
		if !entry.IsDir() {
			keys = append(keys, &systemModel.SSHKey{
				Name: entry.Name(),
				Path: filepath.Join(sshDir, entry.Name()),
			})
		}
	}

	response.Success(c, keys)
}

// testConnectionReq extends the protobuf TestConnectionRequest with a
// CredentialID field so the handler can resolve auth through the credential
// system instead of relying on deprecated AuthType/AuthKey/AuthSecret fields.
type testConnectionReq struct {
	systemModel.TestConnectionRequest
	CredentialID uint `json:"credential_id"`
}

// TestConnection .
// @router /api/v1/system/test-connection [POST]
func TestConnection(ctx context.Context, c *app.RequestContext) {
	var req testConnectionReq
	if err := c.BindAndValidate(&req); err != nil {
		response.BadRequest(c, err.Error())
		return
	}

	gitSvc := git.NewGitService()
	authSvc := auth.NewAuthService()

	var err error

	if req.CredentialID > 0 {
		// Credential system: resolve auth from credential ID
		isDBKey := authSvc.IsCredentialDBKey(req.CredentialID)
		if isDBKey {
			privateKey, passphrase, keyErr := authSvc.GetCredentialKeyContent(req.CredentialID)
			if keyErr != nil {
				response.Success(c, map[string]string{"status": "failed", "error": "failed to load credential: " + keyErr.Error()})
				return
			}
			err = gitSvc.TestRemoteConnectionWithDBKey(req.Url, privateKey, passphrase)
		} else {
			authMethod, authErr := authSvc.ResolveCredential(req.CredentialID)
			if authErr != nil {
				response.Success(c, map[string]string{"status": "failed", "error": "failed to resolve credential: " + authErr.Error()})
				return
			}
			if authMethod.Type == gitbackend.AuthNone {
				err = gitSvc.TestRemoteConnection(req.Url)
			} else {
				// For HTTP-type credentials, use HTTP test method
				err = gitSvc.TestRemoteConnectionWithHTTP(req.Url, "", "")
			}
			_ = authMethod
		}
	} else {
		// Fallback: resolve auth through auth service (which handles
		// the deprecated AuthType/AuthKey/AuthSecret fields internally)
		authConfig, resolveErr := authSvc.ResolveAuthFromParams(req.AuthType, req.AuthKey, req.AuthSecret, 0)
		if resolveErr != nil {
			response.Success(c, map[string]string{"status": "failed", "error": "failed to resolve auth: " + resolveErr.Error()})
			return
		}

		switch req.AuthType {
		case "ssh_db", "ssh_database":
			if strings.HasPrefix(req.AuthKey, "credential:") {
				credIDStr := strings.TrimPrefix(req.AuthKey, "credential:")
				credID := parseUint(credIDStr)
				if credID > 0 {
					privateKey, passphrase, keyErr := authSvc.GetCredentialKeyContent(credID)
					if keyErr != nil {
						response.Success(c, map[string]string{"status": "failed", "error": "failed to load credential: " + keyErr.Error()})
						return
					}
					err = gitSvc.TestRemoteConnectionWithDBKey(req.Url, privateKey, passphrase)
				} else {
					err = fmt.Errorf("invalid credential ID")
				}
			} else {
				err = gitSvc.TestRemoteConnectionWithDBKey(req.Url, req.AuthKey, req.AuthSecret)
			}
		case "ssh_local":
			err = gitSvc.TestRemoteConnectionWithLocalKey(req.Url, req.AuthKey, req.AuthSecret)
		case "http", "https":
			err = gitSvc.TestRemoteConnectionWithHTTP(req.Url, req.AuthKey, req.AuthSecret)
		default:
			if authConfig.Type != gitbackend.AuthNone {
				err = gitSvc.TestRemoteConnection(req.Url)
			} else {
				err = gitSvc.TestRemoteConnection(req.Url)
			}
		}
	}

	if err != nil {
		response.Success(c, map[string]string{"status": "failed", "error": err.Error()})
		return
	}

	response.Success(c, map[string]string{"status": "success"})
}

// parseUint 解析 uint
func parseUint(s string) uint {
	var result uint
	fmt.Sscanf(s, "%d", &result)
	return result
}

// GetRepoStatus .
// @router /api/v1/system/repo/status [GET]
func GetRepoStatus(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	status, err := gitSvc.GetStatus(repo.Path)
	if err != nil {
		response.InternalServerError(c, err.Error())
		return
	}

	response.Success(c, map[string]string{"status": status})
}

// GetRepoGitConfig .
// @router /api/v1/system/repo/git-config [GET]
func GetRepoGitConfig(ctx context.Context, c *app.RequestContext) {
	repoKey := c.Query("repo_key")
	if repoKey == "" {
		response.BadRequest(c, "repo_key is required")
		return
	}

	repo, err := db.NewRepoDAO().FindByKey(repoKey)
	if err != nil {
		response.NotFound(c, "repo not found")
		return
	}

	gitSvc := git.NewGitService()
	name, email, _ := gitSvc.GetGitUser(repo.Path)

	response.Success(c, map[string]string{
		"name":  name,
		"email": email,
	})
}

// SubmitChanges .
// @router /api/v1/system/repo/submit [POST]
func SubmitChanges(ctx context.Context, c *app.RequestContext) {
	handler.BindAndDo(c,
		func(req *systemModel.SubmitChangesRequest) (map[string]string, error) {
			if req.Message == "" {
				return nil, handler.ErrBadRequest("commit message is required")
			}

			repo, err := db.NewRepoDAO().FindByKey(req.RepoKey)
			if err != nil {
				return nil, handler.ErrNotFound("repo not found")
			}

			gitSvc := git.NewGitService()

			// Selective file staging or add all
			if len(req.Files) > 0 {
				if err := gitSvc.AddFiles(repo.Path, req.Files); err != nil {
					return nil, handler.ErrInternal("Failed to stage files: " + err.Error())
				}
			} else {
				if err := gitSvc.AddAll(repo.Path); err != nil {
					return nil, handler.ErrInternal("Failed to stage files: " + err.Error())
				}
			}

			status, _ := gitSvc.GetStatus(repo.Path)
			fullMsg := fmt.Sprintf("%s\n\nGit Status Snapshot:\n%s", req.Message, status)

			if err := gitSvc.Commit(repo.Path, fullMsg, req.AuthorName, req.AuthorEmail); err != nil {
				_ = gitSvc.Reset(repo.Path)
				return nil, handler.ErrInternal("Failed to commit: " + err.Error())
			}

			msg := "Committed successfully"

			if req.Push {
				if err := gitSvc.PushCurrent(repo.Path); err != nil {
					msg += ", but push failed: " + err.Error()
					c.Set("audit_target", "repo:"+repo.Key)
					return map[string]string{"message": msg, "warning": "push_failed"}, nil
				}
				msg += " and pushed to remote"
			}

			c.Set("audit_target", "repo:"+repo.Key)
			return map[string]string{"message": msg}, nil
		},
	)
}

// GetAppInfo 获取应用版本信息
// @router /api/v1/system/app-info [GET]
func GetAppInfo(ctx context.Context, c *app.RequestContext) {
	response.Success(c, map[string]string{
		"app_name":   appinfo.AppName,
		"version":    appinfo.Version,
		"build_time": appinfo.BuildTime,
		"git_commit": appinfo.GitCommit,
	})
}

// SelectDirectory 打开系统目录选择对话框
// @router /api/v1/system/select-directory [POST]
func SelectDirectory(ctx context.Context, c *app.RequestContext) {
	var req struct {
		Title string `json:"title"`
	}
	_ = c.Bind(&req)

	title := req.Title
	if title == "" {
		title = "选择目录"
	}

	// 尝试根据操作系统打开目录选择对话框
	var result string
	var err error

	switch runtime.GOOS {
	case "darwin":
		// macOS: 使用 osascript
		script := fmt.Sprintf(`tell application "System Events" to activate
return POSIX path of (choose folder with prompt "%s")`, title)
		result, err = execCommand("osascript", "-e", script)
	case "windows":
		// Windows: 使用 powershell
		cmd := fmt.Sprintf(`Add-Type -AssemblyName System.Windows.Forms; $f = New-Object System.Windows.Forms.FolderBrowserDialog; $f.Description = '%s'; $f.ShowDialog() | Out-Null; if ($f.SelectedPath) { Write-Output $f.SelectedPath }`, title)
		result, err = execCommand("powershell", "-Command", cmd)
	default:
		// Linux 或其他系统: 返回错误，建议使用目录浏览功能
		errorMsg := "Directory dialog not supported on this platform. Please use the directory browser instead."
		response.InternalServerError(c, errorMsg)
		return
	}

	if err != nil {
		// 检查是否是用户取消
		errMsg := err.Error()
		if strings.Contains(errMsg, "User canceled") || strings.Contains(errMsg, "用户取消") || strings.Contains(errMsg, "用户已取消") || strings.Contains(errMsg, "-128") {
			response.Success(c, map[string]string{"path": "", "cancelled": "true"})
			return
		}
		// 提供备选方案：使用目录浏览功能
		errorMsg := "Failed to open directory dialog: " + errMsg + ". Please use the directory browser instead."
		response.InternalServerError(c, errorMsg)
		return
	}

	path := strings.TrimSpace(result)
	if path == "" {
		response.Success(c, map[string]string{"path": "", "cancelled": "true"})
		return
	}

	response.Success(c, map[string]string{"path": path, "cancelled": "false"})
}

// execCommand 执行系统命令并返回输出
func execCommand(name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		// 返回包含 stderr 的详细错误信息
		return "", fmt.Errorf("%v: %s", err, strings.TrimSpace(string(output)))
	}
	return string(output), nil
}
