syntax = "proto2";

package maintenance;

import "api.proto";
import "common.proto";

option go_package = "/maintenance";

message HealthRequest {
    optional string repo_key = 1 [(api.path) = "repo_key"];
}

message SlimRequest {
    optional string repo_key = 1 [(api.path) = "repo_key"];
    repeated string paths = 2 [(api.body) = "paths"];
    optional bool add_gitignore = 3 [(api.body) = "add_gitignore"];
}

message GitignoreRequest {
    optional string repo_key = 1 [(api.path) = "repo_key"];
    repeated string paths = 2 [(api.body) = "paths"];
}

message MaintenanceTaskResponse {
    optional common.BaseResponse base = 1;
    optional string task_id = 2;
}

message ListRecordsRequest {
    optional string repo_key = 1 [(api.path) = "repo_key"];
    optional int32 page = 2 [(api.query) = "page"];
    optional int32 page_size = 3 [(api.query) = "page_size"];
}

message GetRecordRequest {
    optional string repo_key = 1 [(api.path) = "repo_key"];
    optional uint32 id = 2 [(api.path) = "id"];
}

message AIAnalyzeRequest {
    optional string repo_key = 1 [(api.path) = "repo_key"];
    repeated string file_paths = 2 [(api.body) = "file_paths"];
    optional int64 threshold = 3 [(api.body) = "threshold"];
}

service MaintenanceService {
    rpc Health(HealthRequest) returns (MaintenanceTaskResponse) {
        option (api.get) = "/api/v1/repo/:repo_key/maintenance/health";
    }

    rpc Slim(SlimRequest) returns (MaintenanceTaskResponse) {
        option (api.post) = "/api/v1/repo/:repo_key/maintenance/slim";
    }

    rpc GC(HealthRequest) returns (MaintenanceTaskResponse) {
        option (api.post) = "/api/v1/repo/:repo_key/maintenance/gc";
    }

    rpc Gitignore(GitignoreRequest) returns (MaintenanceTaskResponse) {
        option (api.post) = "/api/v1/repo/:repo_key/maintenance/gitignore";
    }

    rpc ListRecords(ListRecordsRequest) returns (MaintenanceTaskResponse) {
        option (api.get) = "/api/v1/repo/:repo_key/maintenance/records";
    }

    rpc GetRecord(GetRecordRequest) returns (MaintenanceTaskResponse) {
        option (api.get) = "/api/v1/repo/:repo_key/maintenance/records/:id";
    }

    rpc AIAnalyze(AIAnalyzeRequest) returns (MaintenanceTaskResponse) {
        option (api.post) = "/api/v1/repo/:repo_key/maintenance/ai-analyze";
    }
}
